Network errors are now handled, new error sound effect.

diff --git a/bin/mrec b/bin/mrec
--- a/bin/mrec
+++ b/bin/mrec
@@ -20,7 +20,14 @@ elif [ "$1" = "" ]; then #stop recording
 	while [ -e "/proc/$pid" ]; do sleep 0.1; done
 
 	mupload ~/.mrecfile.ogv "vid/${name}.ogv"
-	msound ding.mp3
+
+	if [ $? -eq 0 ]; then
+		msound ding.mp3
+	else
+		msound error.mp3
+		echo "An error occurred." 1>&2
+		exit 1
+	fi
 else #start recording
 	rm ~/.mrecfile.ogv &>/dev/null
 	rm ~/.mrecname &>/dev/null
diff --git a/bin/mshot b/bin/mshot
--- a/bin/mshot
+++ b/bin/mshot
@@ -7,6 +7,12 @@ fi
 sleep 0.1
 DIR=`mktemp -d`
 scrot "$DIR/pic.png"
-msound camera-shutter.mp3
 
 mupload "$DIR/pic.png" "img/${1}.png"
+if [ $? -eq 0 ]; then
+	msound camera-shutter.mp3
+else
+	msound error.mp3
+	echo "An error occurred." 1>&2
+	exit 1
+fi
